name: 'ServiceNow DevOps SBOM Scan Results'
description: 'Send SBOM Information to ServiceNow Devops'
inputs:
  instance-url: 
    description: 'ServiceNow Instance URL'
    required: true
  devops-integration-user-name:
    description: 'Devops Integration User Name'
  devops-integration-user-password:
    description: 'Devops Integration User Password'
  devops-integration-token:
    description: 'Devops Integration Token'
    required: false
  context-github:
    description: 'Github Context'
    required: true
  job-name:
    description: 'Display Name of the Job'
    required: true
  tool-id:
    description: 'Orchestration Tool Id'
    required: true
  file-path:
    description: 'SBOM File Path'
    required: true
  model-id:
    description: 'SBOM Model Id'
branding:
  icon: 'refresh-ccw'
  color: 'green'
runs: 
  using: 'node12'
  main: 'dist/index.js'
