name: 'ServiceNow DevOps Sonar Scan Results'
description: 'Send Sonar Information to ServiceNow Devops'
inputs:
  instance-url: 
    description: 'ServiceNow Instance URL'
    required: true
  devops-integration-user-name:
    description: 'Devops Integration User Name'
  devops-integration-user-password:
    description: 'Devops Integration User Password'
  devops-integration-token:
    description: 'Devops Integration Token'
    required: false
  security-tool-id:
    description: 'Security Tool Id'
    required: true
  context-github:
    description: 'Github Context'
    required: true
  job-name:
    description: 'Display Name of the Job'
    required: true
  security-result-attributes: 
    description: 'Security Results Attributes: For more information on defining the security attributes, View full Marketplace listing link above'
    required: true
  tool-id:
    description: 'Orchestration Tool Id'
    required: true
branding:
  icon: 'refresh-ccw'
  color: 'green'
runs: 
  using: 'node12'
  main: 'dist/index.js'
