name: Test

on:
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Compile
      run: npm run build

  SecurityScanResults:
    needs: build
    runs-on: ubuntu-latest
    name: Servicenow Security Scan Results

    steps:
      - name: Servicenow Security Scan Results
        uses: maheshganji/custom-action-get@sonar
        with:
          devops-integration-user-name: 'devops.system'
          devops-integration-user-password: 'Test@123'
          instance-url: 'https://sumitdtokyo2.service-now.com/'
          tool-id: 'db6f247783626910566ace40ceaad326'
          context-github: ${{ toJSON(github) }}
          job-name: 'Build'
          security-tool-id: '3f3382b4479a615060f22fe4126d431d'
          security-result-attributes: '{ "applicationName": "VeracodeAPP", "buildVersion": "V1" }'
